### PR TITLE
for fixing the depencie conflit with react 18

### PR DESCRIPTION
**Pull request by ramsesndame237**

### CODE REVIEW

**Comment by manuelLandreau** [comment]
@oliviertassinari it would be great to merge this one, thanx !

**Comment by skrln** [comment]
@oliviertassinari Hey Oliver. Merging this one would be super helpful. Thanks!

**Comment by steps371** [comment]
@ramsesndame237 indenting changes in the package.json seems unnecessary, maybe that's holding up the pr?

**Comment by ramsesndame237** [comment]
so i can merge it

**Review by skrln — APPROVED** [review]

**Comment by anton-mph** [comment]
What is ETA for React 17/18 compatible version?

**Comment by ESalih-Dev** [comment]
@caleb-harrelson  @vanhoutenbos I believe you guys also have write permission to this repo?

Is this a PR you can review + merge?

**Comment by sanderkooger** [comment]
I would love to see this one merged!

**Comment by ndueber** [comment]
Getting this merged would be super helpful! I dont want to downgrade react to use this library!

**Comment by ian-uesseler-fivestars** [comment]
Would love this to be merged 👍

**Comment by sanderkooger** [comment]
When will this be merged?

**Comment by sanderkooger** [comment]
@oliviertassinari could you merge this please?

**Comment by rodrigo-galdeano-fivestars** [comment]
cc @meowtec

**Comment by meowtec** [comment]
> cc @meowtec

I have no permission to do that. I am not a collaborator of this project.

**Review by HazyFish — APPROVED** [review]

**Comment by zoraxl** [comment]
Please merge this PR, really appreciate it!!

**Comment by iacobfred** [comment]
@oliviertassinari, I don't see any response here from a project maintainer. Is this package unmaintained?

**Comment by steps371** [comment]
@oliviertassinari, can we assume some of this repo's functionality will be included in the upcoming MUI X Carousel on the roadmap? I know it's still in the 'planning to build' phase.

I can also not find any suggestions of using this library any in MUI docs which probably means we should start looking for alternatives if no maintainer can be found

**Comment by oliviertassinari** [comment]
@steps371 this project has no affiliations with MUI. At least, so far we never discussed the option to move it. I agree, I think that it would be awesome to find an alternative to my repository. I would like to archive it, but it would prevent the community to collaborate on GitHub so I'm not doing it.

**Comment by steps371** [comment]
Thanks for the explanation @oliviertassinari. The main reason I started using the package was recommended by MUI documentation, so it used to have some affiliation, but got removed at some point this year.

I will do some digging on alternatives and post some suggestions for anyone interested

**Comment by ndueber** [comment]
@steps371 @oliviertassinari 

Hey all, I also came to this package due to the MUI reference. I was able to use this library just by forcing npm to have some conflicting dependencies. it worked fine with react 18. 

However I ended up moving away from this library due to some limitations of the package and the lack of support. I ended up using [Embla Carousel](https://www.embla-carousel.com/get-started/react/). The library didn't have as many examples as this libraary, however it was customizable enough and had enough examples for me to get what i needed.

**Comment by Fermain** [comment]
I also found my way here via MUI docs and ended up using [Strapi](https://docs.strapi.io/developer-docs/latest/developer-resources/content-api/integrations/react.html)

**Comment by oliviertassinari** [comment]
I'm closing per https://github.com/oliviertassinari/react-swipeable-views/issues/676, thanks for having a look at it.

**Comment by slavko-clubee** [comment]
I can't use it with React 18.3
`npm install --save react-swipeable-views`

```
npm error Could not resolve dependency:
npm error peer react@"^15.3.0 || ^16.0.0 || ^17.0.0" from react-swipeable-views@0.14.0
npm error node_modules/react-swipeable-views
npm error   react-swipeable-views@"*" from the root project
```
But, ` npm i react-swipeable-views-react-18-fix` works

**Pull request closed without merging**
