### PR TITLE
Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps …

### PR DESCRIPTION
**Pull request by mjunaidi**
…to suppress warning

### CODE REVIEW

**Comment by jeanpoelie** [comment]
Could you please fix the conflicts? I will than take a look at the PR, test it and possibly merge it to remove warnings :)

**Comment by pahund** [comment]
When may we expect a new version that contains this fix? 😀
Thank you for your work!

**Comment by jeanpoelie** [comment]
Hi!

i am currently working on building an unstable release version so that I can test the package in our production product, I will let you know if the unstable version is ready and will create a release when it is tested.

**Comment by jeanpoelie** [comment]
I just released a ReleaseCandidate, if you can test it with me that would  be amazing! I have not seen any errors on the UNSAFE part yet! https://www.npmjs.com/package/react-swipeable-views

**Comment by pahund** [comment]
🤔 it seems the fix did not make it into release 0.13.9, did it?

**Pull request merged**
