### PR TITLE
Fix get display same slide

### LINKED ISSUE #440: getDisplaySameSlide returns true when children aren't keyed
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

With the following code (truncated for readability)

```jsx
<SwipeableView index={this.state.index}>
  {this.props.children}
</SwipeableView>

<Button onClick={this.incrementIndex} />
```

Clicking the button should animate the slides.

## Current Behavior

Clicking the button changes the slides without animation.

I think this is because [this line](https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views-core/src/getDisplaySameSlide.js#L8) is checking for an exact equivalence instead of checking for `undefined` OR `null`.

If I don't provide keys to my children, the key is `undefined`, and it (I think) erroneously enters the control flow.

I'm using Preact, so maybe it's different for React. But regardless, making the inequality sign `!=` instead of `!==` seems semantically correct.

What do you think?

## Steps to Reproduce (for bugs)

Will provide if needed. I'm suggesting an exact code change instead so I don't think this is needed.

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |         |
| React                  |         |
| platform               |         |
| etc                    |         |

### LINKED ISSUE #476: Transition broken when rendering dynamic children
Reproduction case:
https://codesandbox.io/s/kw938wq8j3

1)Content of Tab 1 & 2 are rendered explicitely in code, content of tabs 3-8 are rendered from an array. All tabs have unique keys
2)Transition works when moving from OR to one of the first three tabs
3)Transition doesn't work when moving from tab 4-8 to another tab in the 4-8 range

Quickly looking at code, I see that in tabs 4-8 the state of the component has displaySameSlide:
true, that causes the transition to be removed.  Probably because the code in getDisplaySameSlide sees all entries in the array as the same child

### PR DESCRIPTION
**Pull request by MastroLindus**
Close #440
Close #476
Close #498

### CODE REVIEW

**Comment by MastroLindus** [comment]
@oliviertassinari  I know you are busy with material-ui, however as you are the only maintainer it would be really appreciated if you could take the time to review and merge this PR when you can.
It only changes one file (and one additional test that would fail before and it is now passing) so it should take just a few minutes, and it fixes 2 currently open issues.
Appreciated!

**Comment by Benew** [comment]
hum hi. I really need this. @MastroLindus could you squash your commits so that the review gets smooth ?

**Comment by Benew** [comment]
@MastroLindus trying to make another PR #498 but I didn't expect the tests to support null children.

Did you find a workaround ?

**Comment by Benew** [comment]
@oliviertassinari is there a reason why this is not merged (other than lack of time to maintain this and review the code I mean) ?
This issue is a huge one (to me)

**Comment by oliviertassinari** [comment]
@MastroLindus Well done, I'm sorry for the delay.

**Comment by Benew** [comment]
@oliviertassinari better late than never! Thank you and @MastroLindus

**Comment by Benew** [comment]
@oliviertassinari are you going to publish an update to npm ?

**Comment by oliviertassinari** [comment]
I'm cutting a release.

**Pull request merged**
