### PR TITLE
Fixing deprecated UNSAFE_* warnings in the console

### PR DESCRIPTION
**Pull request by korbav**
- Removing all the UNSAFE_* calls and replacing them with mixed usage of : 

   - `componentDidUpdate`
   - `getSnapshotBeforeUpdate`
   - `constructor`

- Adapting one test to reflect the change

### CODE REVIEW

**Comment by korbav** [comment]
Hi @oliviertassinari , could you please take a look? 👍

**Comment by kelexel** [comment]
Bump
Please merge when possible, I am migrating from React 16.x to 17.x in order to support new MUI(-x) ;)

**Comment by buigabor** [comment]
A merge would be lovely ;)

**Comment by simonjohansson** [comment]
I wholehartedly concur

**Comment by Grsmto** [comment]
I have published this PR on NPM if that can be useful for anyone. Add it like this in your package.json: 
`"react-swipeable-views": "npm:@gromy/react-swipeable-views@^0.15.0",`

**Comment by nevolgograd** [comment]
@Grsmto thanks, but your fork throws this: 
```
Module not found: Error: Can't resolve 'react-swipeable-views-core' in '.../react-swipeable-views/lib'
```

rm -rf node_modules and lock file doesn’t help.

**Comment by Grsmto** [comment]
@nevolgograd could you try again with `0.15.1`?

**Comment by nevolgograd** [comment]
@Grsmto noice, error gone. Thanks!

**Comment by nevolgograd** [comment]
@korbav is it possible to fix unsafe methods for `react-swipeable-views-utils` also? [There are](https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views-utils/src/virtualize.js) only two of them.

**Comment by korbav** [comment]
> @Grsmto @korbav is it possible to fix unsafe methods for `react-swipeable-views-utils` also? [There are](https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views-utils/src/virtualize.js) only two of them for each util. Would really appreciate it.

@nevolgograd This PR already includes a fix for it

https://github.com/korbav/react-swipeable-views/blob/edf1e98210a20a5dab80aa96fc16cf5acfb850eb/packages/react-swipeable-views-utils/src/virtualize.js#L29-L50

**Comment by millermeares** [comment]
any chance we could get a merge on this?

**Comment by kgaregin** [comment]
@oliviertassinari hey man, would be cool to merge this finally <3 thanks

**Comment by NawarA** [comment]
Bumping this, so it gets merged

**Comment by xmcodings** [comment]
why is this pr still not merged? im confused... 😢

**Comment by simonjohansson** [comment]
Hello! 👋 
Its me, the weekly merge reminder.

**Comment by NawarA** [comment]
@oliviertassinari can you merge this PR or assign someone to merge? A lot of developers are passionate about this issue and waiting for a merge, thank you 🙏

**Comment by wesleyBBD** [comment]
Hi guys, can we please get this merged!

**Comment by nd-kurnal** [comment]
MERGE THIS

**Comment by NawarA** [comment]
I have nothing but love for the folks behind this package, but I had to drop this dep. 

Its outdated, and in my opinion, deprecated.

PS: I used [CSS Scroll Snapping](https://css-tricks.com/practical-css-scroll-snapping/) to accomplish something similar in my app.

Much love to everyone

**Comment by oliviertassinari** [comment]
I'm closing per https://github.com/oliviertassinari/react-swipeable-views/issues/676, thanks for having a look at it.

**Comment by shopglobal** [comment]
why not merge it

**Comment by shopglobal** [comment]
NPM supports installing from git repos;

example:
```
npm i --save-dev oliviertassinari/react-swipeable-views#pull/654/head --force
```

**Comment by lucasaljalali** [comment]
> I have published this PR on NPM if that can be useful for anyone. Add it like this in your package.json: `"react-swipeable-views": "npm:@gromy/react-swipeable-views@^0.15.1",`

Thanks man!

**Comment by rafaelpanayiotou** [comment]
kmx kxm?! why current PR is closed?

**Comment by designly1** [comment]
I forked and released a new version of this package. Works with React 19. Also has type declaration file included, so no need to use definitely typed package.

https://www.npmjs.com/package/react-swipeable-views-new

**Pull request closed without merging**
