### PR TITLE
Migrate to import * as React from 'react'

### PR DESCRIPTION
**Pull request by kodai3**
```diff
- import React from 'react'
+ import * as React from 'react'
```

reference
https://github.com/facebook/react/pull/18102
https://github.com/mui-org/material-ui/pull/19802

### CODE REVIEW

**Comment by caleb-harrelson** [comment]
At what version of React does this become required? I don't see anything about this listed as a breaking change for v17 and [this comment](https://github.com/facebook/react/pull/18106#issuecomment-591093713) seems to indicate it won't affect ES Module imports like we have here, just CommonJS `require`s.

**Comment by kodai3** [comment]
I could not find at what version https://github.com/facebook/react/pull/18106 released, but named export is released some where at v16.x.
v16.13.1 already has no default export, so default exporting is already not technically correct.
 https://github.com/facebook/react/blob/v16.13.1/packages/react/src/React.js

My understanding is bundlers make default export work on ESM(separate entry points), so the change did not affect ESM, but will do with transition period.

https://github.com/facebook/react/pull/18102#issue-378545069

**Comment by atnpcg** [comment]
I haven't seen anywhere on react that default export is not longer available.
all of their docs they still use 
`import React from 'react'`

**Comment by caleb-harrelson** [comment]
Closing this as unnecessary until we see more documentation about it being required.

**Pull request closed without merging**
