### PR TITLE
Added offset update in componentWillReceiveProps

### PR DESCRIPTION
**Pull request by tomwalters**
This enables a change the `index` prop on to update the active view.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@tomwalters Hi, what's your issue? Is this regarding iOS or Android?

**Comment by tomwalters** [comment]
On iOS changing the index wouldn't actually change the active slide for me, this code seems to resolve it

**Comment by oliviertassinari** [comment]
@tomwalters Thanks, that's working :+1:.
However, there is no transition when we switch from active slide. That's a missing feature that 
`index.native.animated.js` does support.

**Comment by tomwalters** [comment]
@oliviertassinari Happy to look at an animation for a new PR, just didn't want to bring in the 'animated' aspect for scroll?

**Comment by oliviertassinari** [comment]
@tomwalters I'm not sure to understand.
To clarify, I do think that the transition between slide should be animated by default (as it's with the browser version.
We could also add a property to disable this feature.

**Comment by tomwalters** [comment]
@oliviertassinari Sounds good, I'll look at it this week and fire over a PR!

**Comment by oliviertassinari** [comment]
Awesome.

**Pull request merged**
