### PR TITLE
Tinder is using react-swipeable-views

### PR DESCRIPTION
**Pull request by roderickhsiao**
[Tinder](https://tinder.com) swipes right on `react-swipeable-views` 🔥 

Thanks for the library! 💙

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@roderickhsiao Awesome!

**Comment by slorber** [comment]
@roderickhsiao do you mean the web or RN version? where?

**Comment by oliviertassinari** [comment]
@slorber Damn, I wish I could log in to Tinder, but I fear my girlfriend retribution 🚒.

**Comment by roderickhsiao** [comment]
@slorber we are using for Tinder web (https://tinder.com)

Its' on your own profile or the recs card (profile card you are swiping on :)) 

screen shot 2018-07-26 at 12 18 21 am
screen shot 2018-07-26 at 12 18 42 am

**Comment by slorber** [comment]
Thanks good to know

I'm more looking for a RN carousel solution so was wondering if this lib RN code was used for the app version (which would have surprised me, does not look exactly the same). Didn't know tinder was available on web too

**Comment by roderickhsiao** [comment]
unfortunately we are not using react native for the native app. And yes, Tinder web is a kind of a hidden product that is not widely known 😅

**Comment by oliviertassinari** [comment]
@slorber I have labeled the react-native (experimental) recently as I have lost interest in the native platform. But the code was definitely working at some point. I have even been working on two different implementations.

**Comment by slorber** [comment]
yes have seen that, and it's still working inside a snack correctly

**Pull request merged**
