### PR TITLE
Fixes iss258

### PR DESCRIPTION
**Pull request by rehnarama**
Simple fix for #258

### CODE REVIEW

**Comment by oliviertassinari** [comment]
Great, thanks!

**Comment by license2e** [comment]
@oliviertassinari Just a heads up, this fix MAY have introduced a noticeable delay in the swipe functionality on mobile devices. I haven't tested builds comparing both, but intend to, and will let you know if this was the cause...

**Comment by license2e** [comment]
Based on my non-scientific tests, there is a perception that version `0.12.2` is a smoother swipe operation than version `0.12.3`.

I dont have the capacity at this moment to record a test of both and overlay them to tell the difference...

**Comment by oliviertassinari** [comment]
Let us know if you find something. Maybe the performance devtools of your browser could help. I haven't notice that delay yet.

**Comment by AlanFoster** [comment]
Does this require a `0.12.3` release of `react-swipeable-views-native` to have this fix?

**Comment by oliviertassinari** [comment]
@AlanFoster No, this change isn't impacting `react-swipeable-views-native`.

**Pull request merged**
