### PR TITLE
Add build:umd command using rollup

### PR DESCRIPTION
**Pull request by dhleong**
See #454

I decided to sit down and roll my sleeves up and came up with a solution. Not sure how you feel about having rollup, but it's only used for the umd build (seems to be what the other project I mentioned did).

Thanks for your time!

### CODE REVIEW

**Comment by dhleong** [comment]
@oliviertassinari it looks like the unit tests are failing due to circle CI's caching being disabled for some reason, but they did pass on the first build. I just changed the exported library name for the packaged UMD to the more canonical `SwipeableViews`. I've run the tests locally and they seem to still pass.

**Comment by dhleong** [comment]
@oliviertassinari I've rebased against master and updated the rollup config for the release version of babel 7

**Comment by jeanpoelie** [comment]
Hi,

Could you resolve the conflicting files for me? I will than test this in a branch and see if I can accept the PR :)

**Comment by dhleong** [comment]
Rebased but haven't checked for outdated dependencies or anything; I've switched to a different build tool for my project that can consume this library directly from NPM, so I don't have a place to test this PR anymore.

**Comment by jeanpoelie** [comment]
I will take the time to test this PR tonight, thank you for the rebase!

**Comment by jeanpoelie** [comment]
Took a bit longer than expected to test, This looks good!

**Pull request merged**
