### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by voleggold**

### CODE REVIEW

**Comment by oliviertassinari** [comment]
🤷‍♂️

**Comment by jsantos** [comment]
This boy is getting famous https://twitter.com/svensauleau/status/1096481692234199042

**Comment by oliviertassinari** [comment]
I'm flattered.

**Comment by voleggold** [comment]
Hello everybody!
I have removed all repo
I am sorry.
Please delete all blogs

**Comment by xtuc** [comment]
Hey @voleggold, I appreciate that you removed the repos. That said, I didn't expect that fame.

**Comment by voleggold** [comment]
Would you please remove twitter blog

**Pull request closed without merging**
