### PR TITLE
Update dom-helpers dependency

### PR DESCRIPTION
**Pull request by firstpersoncode**
This is for #542 

I believe #542 is related to the current issue that I have:
```bash
ERROR in ./node_modules/react-transition-group/esm/CSSTransition.js
Module not found: Error: Can't resolve 'dom-helpers/addClass'

ERROR in ./node_modules/react-transition-group/esm/CSSTransition.js
Module not found: Error: Can't resolve 'dom-helpers/removeClass'
```

### CODE REVIEW

**Comment by jeanpoelie** [comment]
Rolling this back because it is currently breaking a lot due to breaking changes between dom-helper 3.2.1 and 5.1.3

**Comment by kish-ryan** [comment]
@jeanpoelie do i need to install dom-helper ?
I'm getting error  below, it was working fine for me before

./node_modules/react-swipeable-views/lib/SwipeableViews.js
Module not found: Can't resolve 'dom-helpers/transition/properties' in '/Users/ryanweb/Applications/Utility/AppStore/x/node_modules/react-swipeable-views/lib'

**Comment by jeanpoelie** [comment]
Unfortunatly i made the mistake of merging a PR which broke this. The build pipeline didnt see that.  I am currently trying to make a new version withlout the upgraded dom helpers but am having a lot of issues due to me not being at home in npm publish and the owner being a mac user

**Comment by kish-ryan** [comment]
Thanks for quick reply,
Sure, will wait till get resolved

**Comment by jeanpoelie** [comment]
There is a newer version released which is a rollback to 0.13.3, we will be addrresing the issues with the PRs soon

**Pull request merged**
