### PR TITLE
Fix React 0.14.0 warning about findDomNode.

### PR DESCRIPTION
**Pull request by lolJS**
Hey just cleaned up the code a bit cuz I was using this on a project. Also took care of that React 0.14.0 related warning.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@lolJS Thank for this! However regarding the dangling-comma, I'm enforcing them (https://github.com/oliviertassinari/react-swipeable-views/blob/master/.eslintrc#L34)

**Comment by lolJS** [comment]
@oliviertassinari done!

**Comment by oliviertassinari** [comment]
I'm going ahead and merging this.
I will soon release with this change (I have to update the docs first)

**Comment by oliviertassinari** [comment]
@lolJS v0.3.0 was released with your PR.

**Pull request merged**
