### PR TITLE
Allow access to the updateHeight method through ref

### LINKED ISSUE #339: Programmatically trigger updateHeight()
I'm using  react-swipeable-views to animate the Material-UI tabs transition, and I must say I found this library very useful.

However, I enabled the animateHeight property since the height of my slides are very different from each other. It works great when swiping between them or changing tabs, but if the content of the current slide changes, the container doesn't resize.

Is it possible to not only fire the updateHeight() method when the current slide changes, but also when its content change?

### PR DESCRIPTION
**Pull request by stfny222**
Closes #339

### CODE REVIEW

**Comment by oliviertassinari** [comment]
> Maybe we could be exposing a callback property close to the ref pattern to make it work.

Have you considered this option? We could provide a `action` callback property that use can use to trigger actions, this way, we don't encourage people to access private API.

**Comment by stfny222** [comment]
You're totally right. I added a callback property "action" based on the ref pattern, with a parameter "actions" that consists in an object containing all posible actions that could be triggered programmatically (in this case, only the updateHeight function was included).

It can be used like this:

```jsx
<SwipeableViews
  action={actions => {
    this.swipeableActions = actions;
  }}
>
  <div>{'slide n°1'}</div>
  <div>{'slide n°2'}</div>
  <div>{'slide n°3'}</div>
</SwipeableViews>
```

So actions can be called later in your component like this:

```jsx
this.swipeableActions.updateHeight()
```

**Comment by oliviertassinari** [comment]
@stfny222 Sure!

**Comment by oliviertassinari** [comment]
I have some small changes to do. I will take care of it later in the evening :).

**Comment by oliviertassinari** [comment]
@stfny222 Thanks for your resilience!

**Comment by oliviertassinari** [comment]
While I'm on this project, I will fix some issues before releasing.

**Comment by oliviertassinari** [comment]
I have published a new release.

**Comment by ibraude** [comment]
@lotusms Hey, I'm probably way too late on this, but if anyone still finds it relevant I managed to work around the problem you mentioned.  I had the same problem that a certain slide would rerender, change its height, but wouldn't call `updateHeight` for SwipeableViews unless I switched tabs. 
` handleRefresh = () => {
    let oldIndex = this.state.index
    let newIndex = oldIndex + 1
    this.setState({
      index: newIndex,
    })
    this.setState({
      index: oldIndex,
    })
  }`

What I ended up doing is writing the above function that modifies state for the parent component of SwipeableViews, passed it down to the slide component, and had it trigger it every time it rerenders. this forced the parent component of SwipeableViews to rerender, thus fixing the problem. 

Not the most elegant solution, but it works for now. 

Would love to hear if anyone has a better fix. 

Thanks

**Pull request merged**
