### PR TITLE
[Browser] Expose a slideUpdateHeight hook

### LINKED ISSUE #177: animateHeight={true} -> issue with overflow
When the swipeview is initialized with the property animateHeight={true} the the swipeable container behaves as expected: It has the perfect size to fit the content.
But once some list you output withing that container gets highter (e.g. states changes and the map function returns more <li/> elements) the height doesn't change accordingly. You have to swipe to another swipecontainer and then come back again to see the correct height.

Is there an event which I can trigger to recalculate the height once my content changes?

### PR DESCRIPTION
**Pull request by oliviertassinari**
@Nopik Another shot at the issue. Let me know what you think.
I have updated the demo as a starting point for the documentation.

Closes #279.
Closes #177.

### CODE REVIEW

**Comment by Nopik** [comment]
Yeah, seems essentially the same. I'm OK with this.

**Comment by Nopik** [comment]
I'll try that on my app when I'll have a chance, but I expect it will work better than my crude solution so dar.

**Comment by Nopik** [comment]
Just tested it against my app, it works fine, as expected. Looking forward to see that on npm ;)

**Comment by oliviertassinari** [comment]
@Nopik Thanks for letting me know. Let's release it.

**Comment by cstrat** [comment]
Any examples on how we can best implement this?
I've got a slide which contains a truncated list, with a button saying 'show more'... if they hit that then the slides height needs to update.

**Pull request merged**
