### PR TITLE
Added GuestBell to the list of Companies

### PR DESCRIPTION
**Pull request by PeterKottas**
We have a great experience using this lib at @GuestBell for our [PWA app](https://guest.guestbell.com/demo-hotel/app/property). Happy to be included in the list of people who use this if that's ok with you @oliviertassinari .

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@PeterKottas Thanks for sharing

**Comment by PeterKottas** [comment]
Not sure I follow, is this not going to be merged? The comment states:

> Are you using this library? Add your company or project.

Did I miss anything?

**Comment by PeterKottas** [comment]
Hey @oliviertassinari, could you elaborate? Not sure if you closed it by mistake or if you have some extra rules for this that I did not find. Cheers

**Comment by oliviertassinari** [comment]
Hey @PeterKottas I have closed because I don't think that we should restrict the "Who's using" to "brands" developers already know and trust.

**Comment by PeterKottas** [comment]
Sure np. We own/maintain quite a few repos on github. Namely https://github.com/react-page/react-page, https://github.com/PeterKottas/DotNetCore.WindowsService, https://github.com/PeterKottas/react-bell-chat and contribute to dozens of others. But no big deal, I just noticed the section when looking up information about a problem we were seeing with the lib. Obviously incomparable with the likes of big companies but we are a fierce small startup :) 

Maybe 

> Are you using this library? Add your company or project.

Needs some clarification.

**Pull request closed without merging**
