### PR TITLE
Set transition to zero while updating transform directly to container…

### LINKED ISSUE #431: Slide transition animation breaks down with heavy enough slides
In certain conditions, the slide change animation "jumps back" after arriving to the next slide, repeating the animation.

- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
The slide change animation plays once.

## Current Behavior
This happens with using virtualize (at least), and creating large slides that are heavy to render.
Lets assume the `overscanSlideAfter `and `overscanSlideBefore` props are both 1.
During a slide change, there will be a brief moment, where the DOM has 4 children in the containerNode. After React settles its rendering, there are 3 children as there are supposed to be.

For example, when sliding right, the transform goes from `translate(-100%, 0px);` to  `translate(-200%, 0px);`. Then, in the `setIndexCurrent`-method, the transform is set back to -100 (as the leftmost child is dropped out). This is set directly to the ref with `this.containerNode.style`.

In the end, there are 4 children, translate at -100%, and transition with animation. The browser starts animating a slide change, before the DOM is updated with removal of the leaving child slide. This behaviour can be fixed with setting `this.containerNode.style.transition = 'all 0s ease 0s';` until React can do its thing.

## Steps to Reproduce (for bugs)
Described above.

## Context
Our project uses react-swipeable-views to show slides the size of the page, with iframes etc inside. They are pretty heavy to move then. I suppose this does not affect lighter examples.

## Your Environment

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |    	v0.12.13     |
| React                  |     16.3.2    |

### PR DESCRIPTION
**Pull request by kallehjerppe**
This should fix #431.
I have only considered the immediate issue, not other parts of the project (like native).

### CODE REVIEW

**Comment by kallehjerppe** [comment]
Hey! Any comments @oliviertassinari? :)

**Comment by oliviertassinari** [comment]
Sorry, I'm focusing my time on Material-UI. I will try to review this pull-request at some point.

**Comment by xAlstrat** [comment]
> Sorry, I'm focusing my time on Material-UI. I will try to review this pull-request at some point, maybe.

I have the same problem, my components are too large. I tried the code shown here and it worked perfectly. Could you merge this pull request please?

**Comment by teetotum** [comment]
I have the IE11 issue [445](https://github.com/oliviertassinari/react-swipeable-views/issues/445) / [407](https://github.com/oliviertassinari/react-swipeable-views/issues/407) (they are really the same issue) and I tried this changeset and it actually fixed the IE11 issue.
Would really appreciate it if this was merged and resulting in a new release.

**Comment by jeanpoelie** [comment]
Hello,

I have tested this PR and approved the changes!

**Comment by germanmitish** [comment]
Greetings! This issue re-appeared and is present at least in 0.13.9 and alpha. I suppose this time the problem is with getDisplaySameSlide. I am not that confident in my quick fix as I had to remove the abovementioned function completely, so I won't make another pull request just yet

**Pull request merged**
