### PR TITLE
New prop to disable height animations

### PR DESCRIPTION
**Pull request by tuomohopia**
Added a new `prop` that allows adjusting the height of the container dynamically but disabling its animation. 

`adjustHeight` is essentially `animateHeight` but with height animations disabled.

Related [issue](https://github.com/oliviertassinari/react-swipeable-views/issues/535) and a [PR](https://github.com/oliviertassinari/react-swipeable-views/pull/536) to fix it.

### CODE REVIEW

**Comment by jeanpoelie** [comment]
I read your previous PR, I agree with this option, some people might not find this deseriable or too much performance heavy, could you fix the conflict for me? I will than test & accept the PR.

**Comment by jeanpoelie** [comment]
@tuomohopia Are you able to resolve the conflicts for me?

**Comment by tuomohopia** [comment]
@jeanpoelie  I've since moved on from this library, but I'll see if I have some time to take a look at this.
What's the actual conflict? Performance issues?

**Comment by jeanpoelie** [comment]
componentDidUpdate seems to be changed after you made the change, I am not sure what code is yours, what is original and what is new. you can see it here: https://github.com/oliviertassinari/react-swipeable-views/pull/537/conflicts

**Pull request merged**
