### PR TITLE
adds support for disabling swipe directions

### PR DESCRIPTION
**Pull request by dasblitz**

### CODE REVIEW

**Comment by dasblitz** [comment]
Ah the pull request was supposed to go into my own fork. I'm using bitbucket normally instead of github so I got confused by the interface. I'll close this one.

**Comment by oliviertassinari** [comment]
@dasblitz Thanks :)

**Comment by dasblitz** [comment]
Mm the setup with Lerna actually makes it a bit harder than expected to just point to my fork in the package.json of the project I need react-swipeable-views for. 

Is it an option to actually merge the pull request in? (It adds two props to prevent forward/backward swiping). It might be to specific to our use case, so I'd understand if you prefer not to. Or if you like the functionality but prefer a different implementation I'd be happy to discuss :)

**Comment by oliviertassinari** [comment]
@dasblitz Can't that feature be already implemented with the existing API? I have at least one closed issue around that matter.

**Comment by dasblitz** [comment]
Ah should have looked in closed issues first my bad, I'll try the #179 solution. Tnx!

**Pull request closed without merging**
