### PR TITLE
Add example for animated height with max-height

### PR DESCRIPTION
**Pull request by ashl1**
In follow to #144

### CODE REVIEW

**Comment by ashl1** [comment]
Sorry, I didn't see your proposal. Why don't I add new demo? Think it's good point to compare two cases.

**Comment by oliviertassinari** [comment]
For simplicity. 
We can add a fourth slide with a width going behond the max height.

**Comment by oliviertassinari** [comment]
@ashl1 I have added an example. Thanks for your help 👍 .

**Comment by ashl1** [comment]
I agree with you about simplicity, but think that is hard to find out this sokution from the demos, especially with no description said about this. It will be better to add "this slide with max-height" at the start of last slide.

**Comment by oliviertassinari** [comment]
> It will be better to add "this slide with max-height" at the start of last slide.

Good idea 😄

**Comment by ashl1** [comment]
Could you add this to not open small PR?

**Comment by oliviertassinari** [comment]
@ashl1 Alright, I'm on it.

**Pull request closed without merging**
