### PR TITLE
Improve ref performance

### PR DESCRIPTION
**Pull request by hartzis**
Great library! I'm the maintainer of [react-swipeable](https://github.com/dogfessional/react-swipeable) and just wanted to see how this library handled some things and noticed these could get "cleaned up" 😸 

- update ref assignment inline functions to use class methods
  - avoids new function creation on each render
  - avoids `null` assignments
  - https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs

~Could probably clean up these lines too after/with this PR:
https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views/src/SwipeableViews.js#L359-L363~
- cleaned up `null` checks 😸 

Let me know, cheers!

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@hartzis Thanks for the pull-request, yes, this can prevent unneeded calls to the ref function when the component rerender.

**Comment by hartzis** [comment]
@oliviertassinari would you like me to include cleaning up those `null` checks in this PR?

**Comment by oliviertassinari** [comment]
@hartzis This would be great :)

**Comment by hartzis** [comment]
@oliviertassinari cleaned up those `null` checks.

Thoughts on the "failing" codecov?

**Comment by oliviertassinari** [comment]
@hartzis I don't care about the test coverage for this project. Thank you!

**Pull request merged**
