### PR TITLE
Fix native vertical scrolling within slide.

### PR DESCRIPTION
**Pull request by oliviertassinari**
This is a continuation of #251, thanks @jmheik for the original PR.
I have updated the demo to take into account your stress test. It's a nice one by the way 😄 .
I have taken what looks like reasonable changes in order to fix the failing demo.

fevr -26-2017 00-31-52

Closes #251.

### CODE REVIEW

**Comment by jmheik** [comment]
Thanks! I'll test it out, and file separate issues if other things noticed in the original PR are still valid.

**Comment by oliviertassinari** [comment]
@jmheik Feel free to open new issues if you find something else not working 👍 .

**Comment by America-first-melon** [comment]
Where is the demo9 of the sample diagram?

**Comment by oliviertassinari** [comment]
@America-first-melon What do you mean?

**Comment by America-first-melon** [comment]
@oliviertassinari  I didn't find this on demo folder.
image

**Comment by oliviertassinari** [comment]
It's not live. Are you using a local fork?

**Comment by America-first-melon** [comment]
@oliviertassinari  No, i used the native example of the home page. And i want to achieve vertical slide on the native. Just in time saw the issues.

**Pull request merged**
