### PR TITLE
Updated componentWillReceiveProps methods

### PR DESCRIPTION
**Pull request by doper1234**
Updated methods using using `npx react-codemod rename-unsafe-lifecycles`. Temporary solution to issue  #534

### CODE REVIEW

**Comment by doper1234** [comment]
@oliviertassinari could this pull request be accepted?

**Comment by uladkasach** [comment]
Looks like this is the solution recommended by react. Checks have passed, its been approved - do we think we can merge this?

p.s. @doper1234 :raised_hands: - thank you from all of us

**Comment by glekner** [comment]
can we merge this?

**Comment by motiejunas** [comment]
@oliviertassinari please

**Comment by alisamonstr** [comment]
@oliviertassinari please

**Comment by nagad814** [comment]
@ValentinMumble please approve

**Comment by caleb-harrelson** [comment]
I pulled this into #616 and merged it.

**Pull request closed without merging**
